### ISSUE TITLE
css images not found

### ISSUE THREAD

**Issue by ghost** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#38] opened 2015-02-17 13:43 UTC
the latest version (on PW 5.19) adds the domain name twice in the path of images.
e.g. http://site.com/sites/www.site.com/site/templates/img/image.png

**Comment by marvinscharle** [comment] 2015-02-17 13:46
Can you please supply the source code? Is this problem only occurring on ProcessWire 2.5.19 or on other versions as well?

Thanks in advance!

**Comment by ghost** [comment] 2015-02-18 00:42
in the head tag I use
<link rel="stylesheet" href="<?php echo AIOM::CSS(array('css/jquery-ui-1.10.2.dark-hive.min.css', 'css/style.css', 'css/lightbox.css', 'css/main.css')); ?>">

An example of the style used in style.css
.topBar { background: url('../img/bgTopBar.png') repeat-x bottom; }

in v3.1.4 that's rendered as
.topBar { background: url('/site/templates/img/bgTopBar.png') repeat-x bottom; }

in v3.2.1 that's rendered as
.topBar { background: url('/sites/www.mydomain.com/site/templates/img/bgTopBar.png') repeat-x bottom; }

Mind that this particular site is a PW 2.5.19 multi-language setup. I haven't encountered it with other setups.

**Comment by marvinscharle** [comment] 2015-02-18 12:55
Hi junofornow,

I cannot reproduce this error. But the folder '/**sites**/domainname.com/site/...' looks to me like there is a problem with the absolute path on the server. 

A few more questions:
1. Is your page located in the folder sites on the server? 
2. Is this problem occurring only on ProcessWire 2.5.19? 
3. If question 1 applies: does this problem still occur if you relocate the site to another folder?

**Comment by ghost** [comment] 2015-02-18 14:49
1/ the root path (ftp) is /public/sites/www.domain.com, but that shouldn't matter, other shared hosting setups I have also point to a "folder", ie. /domains/domain.com/public_html. All of them are publicly available at url http://www.domain.com
2/ I haven't encountered it with other setups
3/ it's not an option to relocate the designated shared hosting physical root folder

**Comment by marvinscharle** [comment] 2015-02-18 15:31
Hi junofornow,

I would suggest you to wait for the next ProcessWire dev version to see if the problem is related to this version.

For now, I recommend you to use the older version of AIOM (that seems to work). 

If you plan to use the latest dev version, I'd be glad if you could tell me whether the problem is fixed after the next ProcessWire update.

**Comment by ghost** [comment] 2015-02-18 15:49
ok, will do, thanks.

**Comment by foobarlab** [comment] 2015-02-19 12:11
I had a similar problem (also using a multilanguage setup of PW 2.5.3, but I am not sure if this does really matter).

My situation: my hosting provider has subfolders in the root which are mapped to subdomain names. Therefore http://beta.example.com has a folder `beta` in the root folder (the root folder is mapped to http://example.com respectively http://www.example.com). When accessing http://beta.example.com the paths inside the minified css files were rewritten with an additional folder `beta` included before the template path. This breaks some relative referenced resources for me (like fonts referenced by `url(...)`).

I solved this by changing the parameters of the UriRewriter call by including the config root path for the rewrite as a second parameter:

```
$_css_src = (!empty($_css_src)) ? Minify_CSS_UriRewriter::rewrite($_css_src, dirname($stylesheet['absolute_path'])) : $_css_src;
```

changed to

```
$_css_src = (!empty($_css_src)) ? Minify_CSS_UriRewriter::rewrite($_css_src, dirname($stylesheet['absolute_path']),wire('config')->paths->root) : $_css_src;
```

**Comment by ghost** [comment] 2015-02-22 12:35
@marvinscharle The problem still persists with PW 2.5.20
@foobarlab Thanks, your source edit solved / fixed the problem.

**Comment by marvinscharle** [comment] 2015-02-23 08:35
Hi guys,

thanks for the feedback. This problem is very strange. Before AIOM 3.1.5 `Minify_CSS_UriRewriter` was called including the root path. This caused a problem (#30), which was fixed by removing the root path. 

It looks like the problem is deeper and located inside the `Minify_CSS_UriRewriter` class. 

We are trying to find a way to solve both issues. For the meantime: please use AIOM 3.1.4 if you encounter this problem.

Thanks!

**Comment by foobarlab** [comment] 2015-02-23 09:43
Hi Marvin,
Thank you! Just another note: actually I have both problems at once while developing a website including your module (which is great BTW!).
First case was already mentioned above (subfolder `beta` for the domain http://beta.example.com/). This is the case when I deploy the website to a remote server (for testing). The other case is when I deploy the website locally (for development): in that case I have a subfolder called `webdev` right after the server name (e.g. [http://localhost/webdev/](http://localhost/webdev/)). For the first case the workaround above fixed it, for the latter case I had to exclude the wire root path again.
I assume the problem is whether the base path to the document root is rewritten or not. For my first case the rewrite base path (`RewriteBase` in `.htaccess`) is `/`, for the other case it is `/webdev`. As we are dealing with absolute paths here it seems like the solution would be to find out what the actual location of the document root is and whether it is rewritten or not. I guess this could be done programmatically but I had no time yet for further investigations.
I hope this sheds some more light on the problem, at least it reflects my cases and I hope it is somehow helpful.
Cheers!

**Closed as completed** 2015-06-29 12:42 UTC
Labels: bug
